### PR TITLE
Sphinx

### PR DESCRIPTION
**Pull request by cchen23**
I adapted the `gendoc/` files from tikreg to use with cottoncandy, and included the generated doc files. (The index of the documetation is in `cottoncandy/docs/index.html`.)

This api reference includes a bunch of modules that are not included in the current cottoncandy documentation (such as `Encryption`, `backend`, and `options`), but I can take those out if needed.

### CODE REVIEW

**Comment by anwarnunez** [comment]
great!
seems a lot of these changes are caused by the change from single to double quotes. i imagine this is due to your editor settings. can you fix that?
re extra modules: yes, please don't include those.
thanks!

**Comment by cchen23** [comment]
> seems a lot of these changes are caused by the change from single to double quotes. i imagine this is due to your editor settings. can you fix that?
Oh, I changed the docstrings with single quotes to use double quotes (because it seemed like most of the docstrings had single quotes). But I can change the ones that had single quotes, back to having single quotes!

**Comment by cchen23** [comment]
> re extra modules: yes, please don't include those.
Okay, I'll update it to just include the `browser`, `utils`, and `interfaces` modules!

**Comment by anwarnunez** [comment]
re quotes: I tend to prefer single quotes. if you want to make a separate pull request to standardize quotes, feel free. i don't know of a strong reason to prefer double quotes over single quotes, but if you have one i'd be happy to comply. on the other hand, if it's a pain to change things back, don't worry about it. just let me know

**Comment by cchen23** [comment]
> re quotes: I tend to prefer single quotes. if you want to make a separate pull request to standardize quotes, feel free. i don't know of a strong reason to prefer double quotes over single quotes, but if you have one i'd be happy to comply. on the other hand, if it's a pain to change things back, don't worry about it. just let me know

Oh, I see. I don't have a particular preference personally, just noticed that some were single and some were double quotes. I've updated the PR to remove the commit that changes from single to double quotes.

**Comment by cchen23** [comment]
I've also updated the PR to only include the browser, interfaces, and utils modules (and `__init__.py`.)

**Comment by anwarnunez** [comment]
ok, i will merge. 
because the pull request is from a fork, the CI tests haven't been ran (unfortunately we can't get around this). once I merge they will run :crossed_fingers:

**Comment by marklescroart** [comment]
Can you possibly re-target the PR to a branch on the main repo? That way you could merge there, then eventually merge to master.

**Comment by anwarnunez** [comment]
This was already merged.

**Pull request merged**
