### PR TITLE
FIX/WIP python 3 compat for read_buffered

### PR DESCRIPTION
**Pull request by eickenberg**
Addressing #29 

@anwarnunez can you check whether this makes sense to you?

### CODE REVIEW

**Comment by anwarnunez** [comment]
Well, this is annoying: "Encrypted environment variables are not available to pull requests from forks due to the security risk of exposing such information to unknown code." (https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml)

Pull requests from forks do not have access to encrypted variables... That's why travis is failing =S

At any rate, the request does not fix #29 
We need to think about it harder.

**Comment by eickenberg** [comment]
OK, this PR forces the target array to be contiguous in memory. Do you need to write to non-contiguous arrays? If so, how often? (I just tried to write to a discontiguous array in python 2.7 and it doesn't work either)

Two ways forward for including writing to discontiguous arrays:
1. if it is not always needed but sometimes nice to have, first play the buffer into a contiguous array and then copy the contents to the non-contiguous target
2. iterate over contiguous subarrays of the non-contiguous array

1 is easy, 2 is quite involved

**Comment by alexhuth** [comment]
I remember we discussed this way back when first setting up the array upload/download. We wanted to avoid *anything* that would duplicate (or worse) the array in memory. We only considered your option (1) and discarded it for that reason, iirc. But maybe not a big deal, I don't know.

**Comment by eickenberg** [comment]
That makes total sense and there is always the design decision/question "If for convenience we cover slow/memory-intensive cases transparently, will this inefficiency be forgotten and the feature overused?"

I am not actually sure what is the precise thing in the tests that works for py27 and doesn't for py3, since flat-out discontiguous arrays don't seem to work with py27 either.

Iterating over contiguous subarrays can amount to iterating over singletons if the subarray is eg `a[::2, ::2, ::2]`. Then it would be very inefficient if written in pure python.

In the end it all boils down to "is this needed or not, and if so, how seldomly?"

**Comment by anwarnunez** [comment]
All tests must pass.

https://github.com/gallantlab/cottoncandy/blob/master/cottoncandy/tests/test_roundtrip.py

They do in PY2 (https://travis-ci.org/gallantlab/cottoncandy/jobs/209080820
).

We can trade off efficiency once we have PY2 and PY3 solutions (with
copying or not).

I wonder if the contiguity error you are seeing is actually due to array
order. This definitely works on PY2. And the array is created and filled so
it's should be contiguous.

Also, given Travis has issues with encrypted env variables and forks, could
you do a pull request from the repo instead of the fork? That way the tests
will be triggered.

**Comment by eickenberg** [comment]
can you point me to the test that fails for py3? Travis is failing for the other reasons we discussed (encryption/aws issues) on the PR

**Comment by eickenberg** [comment]
OK, I'll do the PR from the lab repo.

Array order as in C/F?

I'll see what breaks

**Comment by eickenberg** [comment]
Can't seem to be able to push. Can you add me as a contributor?

**Pull request closed without merging**
